### PR TITLE
v1.0.3

### PR DESCRIPTION
**Pull request by ovaar**
# Change Log

## v1.0.3 (2017-06-21)

**Closed issues:**

- Use unix line ending (\n) instead of \r\n

## v1.0.2 (2017-06-14)

**Closed issues:**

- Remove operation system restrictions in package.json. Now when requiring the package, npm does not throw an error when requiring on windows.

## v1.0.1 (2017-06-08)

**Closed issues:**

- Fixed networking.save() ifaces parameter.

- Increased test coverage

## v1.0.0 (2017-06-02)

**Breaking changes:**

- Rewrote whole package!

**Closed issues:**

- No unit tests for main functions

## v0.0.3
...

### CODE REVIEW

**Comment by hugorodrigues** [comment]
I will be reviewing this in the next days. Thanks for your contribution :)

**Comment by ninox92** [comment]
How's the reviewing?

**Comment by ninox92** [comment]
Bump

**Comment by hugorodrigues** [comment]
Thomas, really sorry for the (super) late reply. I was worried and trying to see if we could maintain backward compatibility but I guess we will just release it as a new major.

I created a new branch (next) to reflect this. Will merge ASAP

**Pull request closed without merging**
